### ISSUE TITLE
qStepCADImport does not build with opencascade 7.6.2

### ISSUE THREAD

**Issue by maz-1** [CloudCompare/CloudCompare#1703]
G:\SRC\CloudCompare\src\plugins\core\IO\qStepCADImport\src\STEPFilter.cpp(232,37): error C2039: 'Nodes': is not a mem
ber of 'Poly_Triangulation' [G:\SRC\CloudCompare\build\plugins\core\IO\qStepCADImport\QSTEP_IO_PLUGIN.vcxproj]

Seems "Poly_Triangulation" no longer has method "Nodes()", need to access nodes via "Node(idx)" instead.

Reference: https://github.com/IfcOpenShell/IfcOpenShell/issues/1883

**Comment by dgirardeau** [comment]
Hi. Thanks for the warning. Is the new syntax retro-compatible? Will it work with old versions?

**Comment by dgirardeau** [comment]
Never mind, it was easy to check that directly on my side ;)

I tried a blind fix: 795d7db4a4c4ddfae38aa9291cfff5fae37e9fab

Can you try it on your side?

**Comment by dgirardeau** [comment]
FYI I've also taken the time to fix the issue with badly oriented triangles when loading STEP files: 3cd9a2a9f577c4c96d968c89fbf54a6f924c52d1

**Comment by maz-1** [comment]
> FYI I've also taken the time to fix the issue with badly oriented triangles when loading STEP files: [3cd9a2a](https://github.com/CloudCompare/CloudCompare/commit/3cd9a2a9f577c4c96d968c89fbf54a6f924c52d1)

Thx, compiles and import STEP files without problem
