### PR TITLE
Fix an error C2666 in ccHObject.h.

### PR DESCRIPTION
**Pull request by buaagy**

### CODE REVIEW

**Comment by buaagy** [comment]
Hi, I'm using msvc2015_64 compiler.
OK, I have changed it to 'static_cast'.

**Comment by dgirardeau** [comment]
I used all versions of Visual Sutdio (now 2017 64 bits) and never had this issue. What is the error message on your side?

**Comment by asmaloney** [comment]
I'd be curious about the actual error you're getting as well since this isn't the correct solution - `CC_TYPES::HIERARCHY_OBJECT` is a `CC_CLASS_ENUM` (which is an `int64_t`).

I wonder if your compiler is having troubles with the anonymous, typed enum:
```cpp
enum : CC_CLASS_ENUM {
```

Could you please try removing your cast and changing this to:
```cpp
enum Flag : CC_CLASS_ENUM {
```

**Comment by buaagy** [comment]
Hi, I tried to remove the 'static_cast" and change it to 'enum Flag : CC_CLASS_ENUM', but the error C2666 still exists.

**Comment by asmaloney** [comment]
OK - I would start by trying to figure out what types the compiler thinks it's dealing with. The types on both sides of the comparison seem very clear :-)

The error doesn't give any more information? Like what 11 overloads it's confused by?

Are you on the last MSVC 2015 (all updates applied)?

**Comment by dgirardeau** [comment]
Oh, that's what I was going to say. Someone already reported to me this issue with Qt 5.12... Is it the only place where the compiler complains?

**Comment by asmaloney** [comment]
For reference, I build with Qt 5.12.0 on macOS without an issue.

Can you please give us the whole error message so we don't have to keep guessing? And are you on the latest/last MSVC 2015 (all updates applied)?

**Comment by buaagy** [comment]
Yes, Qt 5.12 is the only place where the compiler complains. The whole error message is:

`5>D:\cv_work\project\cloudcompare\CloudCompare-source\CloudCompare\libs\qCC_db\ccHObject.h(66): error C2666: 'operator ==': 11 overloads have similar conversions
5>  C:\Qt\Qt5.12.0\5.12.0\msvc2015_64\include\QtGui/qpagelayout.h(93): note: could be 'bool operator ==(const QPageLayout &,const QPageLayout &)'
5>  C:\Qt\Qt5.12.0\5.12.0\msvc2015_64\include\QtGui/qpagesize.h(248): note: or       'bool operator ==(const QPageSize &,const QPageSize &)'
5>  c:\qt\qt5.12.0\5.12.0\msvc2015_64\include\qtgui\qopenglcontext.h(114): note: or       'bool operator ==(const QOpenGLVersionProfile &,const QOpenGLVersionProfile &)'
5>  C:\Qt\Qt5.12.0\5.12.0\msvc2015_64\include\QtGui/qopenglversionfunctions.h(106): note: or       'bool operator ==(const QOpenGLVersionStatus &,const QOpenGLVersionStatus &)'
5>  C:\Program Files (x86)\Windows Kits\8.1\Include\shared\guiddef.h(192): note: or       'bool operator ==(const GUID &,const GUID &)'
5>  C:\Qt\Qt5.12.0\5.12.0\msvc2015_64\include\QtGui/qquaternion.h(184): note: or       'bool operator ==(const QQuaternion &,const QQuaternion &)'
5>  C:\Qt\Qt5.12.0\5.12.0\msvc2015_64\include\QtGui/qvector4d.h(235): note: or       'bool operator ==(const QVector4D &,const QVector4D &)'
5>  C:\Qt\Qt5.12.0\5.12.0\msvc2015_64\include\QtGui/qvector3d.h(235): note: or       'bool operator ==(const QVector3D &,const QVector3D &)'
5>  C:\Qt\Qt5.12.0\5.12.0\msvc2015_64\include\QtGui/qcursor.h(115): note: or       'bool operator ==(const QCursor &,const QCursor &) noexcept'
5>  C:\Qt\Qt5.12.0\5.12.0\msvc2015_64\include\QtGui/qsurfaceformat.h(165): note: or       'bool operator ==(const QSurfaceFormat &,const QSurfaceFormat &)'
5>  C:\Qt\Qt5.12.0\5.12.0\msvc2015_64\include\QtGui/qaccessible.h(443): note: or       'bool operator ==(const QAccessible::State &,const QAccessible::State &)'
5>  C:\Qt\Qt5.12.0\5.12.0\msvc2015_64\include\QtGui/qevent.h(832): note: or       'bool operator ==(QPointingDeviceUniqueId,QPointingDeviceUniqueId) noexcept'
5>  C:\Qt\Qt5.12.0\5.12.0\msvc2015_64\include\QtGui/qevent.h(805): note: or       'bool operator ==(QKeySequence::StandardKey,QKeyEvent *)'
5>  C:\Qt\Qt5.12.0\5.12.0\msvc2015_64\include\QtGui/qevent.h(804): note: or       'bool operator ==(QKeyEvent *,QKeySequence::StandardKey)'
5>  C:\Qt\Qt5.12.0\5.12.0\msvc2015_64\include\QtGui/qvector2d.h(210): note: or       'bool operator ==(const QVector2D &,const QVector2D &)'
5>  c:\qt\qt5.12.0\5.12.0\msvc2015_64\include\qtcore\qstorageinfo.h(103): note: or       'bool operator ==(const QStorageInfo &,const QStorageInfo &)'
5>  c:\qt\qt5.12.0\5.12.0\msvc2015_64\include\qtcore\qrect.h(859): note: or       'bool operator ==(const QRectF &,const QRectF &) noexcept'
5>  c:\qt\qt5.12.0\5.12.0\msvc2015_64\include\qtcore\qrect.h(454): note: or       'bool operator ==(const QRect &,const QRect &) noexcept'
5>  C:\Qt\Qt5.12.0\5.12.0\msvc2015_64\include\QtCore/qsize.h(339): note: or       'bool operator ==(const QSizeF &,const QSizeF &) noexcept'
5>  C:\Qt\Qt5.12.0\5.12.0\msvc2015_64\include\QtCore/qsize.h(169): note: or       'bool operator ==(const QSize &,const QSize &) noexcept'
5>  c:\qt\qt5.12.0\5.12.0\msvc2015_64\include\qtcore\qrandom.h(78): note: or       'bool operator ==(const QRandomGenerator &,const QRandomGenerator &)'
5>  c:\qt\qt5.12.0\5.12.0\msvc2015_64\include\qtcore\qmetaobject.h(201): note: or       'bool operator ==(const QMetaMethod &,const QMetaMethod &)'
5>  c:\qt\qt5.12.0\5.12.0\msvc2015_64\include\qtcore\qmargins.h(372): note: or       'bool operator ==(const QMarginsF &,const QMarginsF &) noexcept'
5>  c:\qt\qt5.12.0\5.12.0\msvc2015_64\include\qtcore\qmargins.h(135): note: or       'bool operator ==(const QMargins &,const QMargins &) noexcept'
5>  C:\Qt\Qt5.12.0\5.12.0\msvc2015_64\include\QtCore/qversionnumber.h(314): note: or       'bool operator ==(const QVersionNumber &,const QVersionNumber &) noexcept'
5>  C:\Qt\Qt5.12.0\5.12.0\msvc2015_64\include\QtCore/qfloat16.h(242): note: or       'bool operator ==(int,qfloat16) noexcept'
5>  C:\Qt\Qt5.12.0\5.12.0\msvc2015_64\include\QtCore/qfloat16.h(242): note: or       'bool operator ==(qfloat16,int) noexcept'
5>  C:\Qt\Qt5.12.0\5.12.0\msvc2015_64\include\QtCore/qfloat16.h(231): note: or       'bool operator ==(float,qfloat16) noexcept'
5>  C:\Qt\Qt5.12.0\5.12.0\msvc2015_64\include\QtCore/qfloat16.h(231): note: or       'bool operator ==(qfloat16,float) noexcept'
5>  C:\Qt\Qt5.12.0\5.12.0\msvc2015_64\include\QtCore/qfloat16.h(230): note: or       'bool operator ==(double,qfloat16) noexcept'
5>  C:\Qt\Qt5.12.0\5.12.0\msvc2015_64\include\QtCore/qfloat16.h(230): note: or       'bool operator ==(qfloat16,double) noexcept'
5>  C:\Qt\Qt5.12.0\5.12.0\msvc2015_64\include\QtCore/qfloat16.h(229): note: or       'bool operator ==(long double,qfloat16) noexcept'
5>  C:\Qt\Qt5.12.0\5.12.0\msvc2015_64\include\QtCore/qfloat16.h(229): note: or       'bool operator ==(qfloat16,long double) noexcept'
5>  C:\Qt\Qt5.12.0\5.12.0\msvc2015_64\include\QtCore/qfloat16.h(216): note: or       'bool operator ==(qfloat16,qfloat16) noexcept'
5>  C:\Qt\Qt5.12.0\5.12.0\msvc2015_64\include\QtCore/qcborcommon.h(95): note: or       'bool operator ==(QCborKnownTags,QCborTag)'
5>  C:\Qt\Qt5.12.0\5.12.0\msvc2015_64\include\QtCore/qcborcommon.h(94): note: or       'bool operator ==(QCborTag,QCborKnownTags)'
5>  C:\Qt\Qt5.12.0\5.12.0\msvc2015_64\include\QtCore/qpoint.h(352): note: or       'bool operator ==(const QPointF &,const QPointF &)'
5>  C:\Qt\Qt5.12.0\5.12.0\msvc2015_64\include\QtCore/qpoint.h(163): note: or       'bool operator ==(const QPoint &,const QPoint &)'
5>  C:\Qt\Qt5.12.0\5.12.0\msvc2015_64\include\QtCore/qvariant.h(590): note: or       'bool operator ==(const QVariant &,const QVariantComparisonHelper &)'
5>  C:\Qt\Qt5.12.0\5.12.0\msvc2015_64\include\QtCore/qhash.h(141): note: or       'bool operator ==(const QHashDummyValue &,const QHashDummyValue &)'
5>  C:\Qt\Qt5.12.0\5.12.0\msvc2015_64\include\QtCore/qstring.h(1784): note: or       'bool operator ==(const QByteArray &,const QStringRef &)'
5>  C:\Qt\Qt5.12.0\5.12.0\msvc2015_64\include\QtCore/qstring.h(1777): note: or       'bool operator ==(const QStringRef &,const QByteArray &)'
5>  C:\Qt\Qt5.12.0\5.12.0\msvc2015_64\include\QtCore/qstring.h(1768): note: or       'bool operator ==(QLatin1String,QStringView) noexcept'
5>  C:\Qt\Qt5.12.0\5.12.0\msvc2015_64\include\QtCore/qstring.h(1761): note: or       'bool operator ==(QStringView,QLatin1String) noexcept'
5>  C:\Qt\Qt5.12.0\5.12.0\msvc2015_64\include\QtCore/qstring.h(1753): note: or       'bool operator ==(QChar,QStringView) noexcept'
5>  C:\Qt\Qt5.12.0\5.12.0\msvc2015_64\include\QtCore/qstring.h(1746): note: or       'bool operator ==(QStringView,QChar) noexcept'
5>  C:\Qt\Qt5.12.0\5.12.0\msvc2015_64\include\QtCore/qstring.h(1738): note: or       'bool operator ==(QStringView,QStringView) noexcept'
5>  C:\Qt\Qt5.12.0\5.12.0\msvc2015_64\include\QtCore/qstring.h(1730): note: or       'bool operator ==(QLatin1String,QChar) noexcept'
5>  C:\Qt\Qt5.12.0\5.12.0\msvc2015_64\include\QtCore/qstring.h(1711): note: or       'bool operator ==(const QStringRef &,QChar) noexcept'
5>  C:\Qt\Qt5.12.0\5.12.0\msvc2015_64\include\QtCore/qstring.h(1692): note: or       'bool operator ==(const QString &,QChar) noexcept'
5>  C:\Qt\Qt5.12.0\5.12.0\msvc2015_64\include\QtCore/qstring.h(1673): note: or       'bool operator ==(const QStringRef &,QLatin1String) noexcept'
5>  C:\Qt\Qt5.12.0\5.12.0\msvc2015_64\include\QtCore/qstring.h(1666): note: or       'bool operator ==(QLatin1String,const QStringRef &) noexcept'
5>  C:\Qt\Qt5.12.0\5.12.0\msvc2015_64\include\QtCore/qstring.h(1637): note: or       'bool operator ==(const QStringRef &,const QString &) noexcept'
5>  C:\Qt\Qt5.12.0\5.12.0\msvc2015_64\include\QtCore/qstring.h(1630): note: or       'bool operator ==(const QString &,const QStringRef &) noexcept'
5>  C:\Qt\Qt5.12.0\5.12.0\msvc2015_64\include\QtCore/qstring.h(1618): note: or       'bool operator ==(const QStringRef &,const QStringRef &) noexcept'
5>  C:\Qt\Qt5.12.0\5.12.0\msvc2015_64\include\QtCore/qstring.h(1263): note: or       'bool operator ==(const char *,QLatin1String)'
5>  C:\Qt\Qt5.12.0\5.12.0\msvc2015_64\include\QtCore/qstring.h(1206): note: or       'bool operator ==(QLatin1String,QLatin1String) noexcept'
5>  C:\Qt\Qt5.12.0\5.12.0\msvc2015_64\include\QtCore/qstring.h(1198): note: or       'bool operator ==(const QString &,QString::Null)'
5>  C:\Qt\Qt5.12.0\5.12.0\msvc2015_64\include\QtCore/qstring.h(1196): note: or       'bool operator ==(QString::Null,const QString &)'
5>  C:\Qt\Qt5.12.0\5.12.0\msvc2015_64\include\QtCore/qstring.h(1194): note: or       'bool operator ==(QString::Null,QString::Null)'
5>  C:\Qt\Qt5.12.0\5.12.0\msvc2015_64\include\QtCore/qstring.h(1719): note: or       'bool operator ==(QChar,QLatin1String) noexcept'
5>  C:\Qt\Qt5.12.0\5.12.0\msvc2015_64\include\QtCore/qstring.h(1700): note: or       'bool operator ==(QChar,const QStringRef &) noexcept'
5>  C:\Qt\Qt5.12.0\5.12.0\msvc2015_64\include\QtCore/qstring.h(1681): note: or       'bool operator ==(QChar,const QString &) noexcept'
5>  C:\Qt\Qt5.12.0\5.12.0\msvc2015_64\include\QtCore/qstring.h(1805): note: or       'bool operator ==(const char *,const QStringRef &)'
5>  C:\Qt\Qt5.12.0\5.12.0\msvc2015_64\include\QtCore/qstring.h(1250): note: or       'bool operator ==(const char *,const QString &)'
5>  C:\Qt\Qt5.12.0\5.12.0\msvc2015_64\include\QtCore/qstring.h(670): note: or       'bool operator ==(const QString &,const QString &) noexcept'
5>  C:\Qt\Qt5.12.0\5.12.0\msvc2015_64\include\QtCore/qbytearray.h(624): note: or       'bool operator ==(const char *,const QByteArray &) noexcept'
5>  C:\Qt\Qt5.12.0\5.12.0\msvc2015_64\include\QtCore/qbytearray.h(622): note: or       'bool operator ==(const QByteArray &,const char *) noexcept'
5>  C:\Qt\Qt5.12.0\5.12.0\msvc2015_64\include\QtCore/qbytearray.h(620): note: or       'bool operator ==(const QByteArray &,const QByteArray &) noexcept'
5>  C:\Qt\Qt5.12.0\5.12.0\msvc2015_64\include\QtCore/qchar.h(611): note: or       'bool operator ==(std::nullptr_t,QChar) noexcept'
5>  C:\Qt\Qt5.12.0\5.12.0\msvc2015_64\include\QtCore/qchar.h(609): note: or       'bool operator ==(QChar,std::nullptr_t) noexcept'
5>  C:\Qt\Qt5.12.0\5.12.0\msvc2015_64\include\QtCore/qchar.h(600): note: or       'bool operator ==(QChar,QChar) noexcept'
5>  D:\cv_work\project\cloudcompare\CloudCompare-source\CloudCompare\libs\qCC_db\ccHObject.h(66): note: while trying to match the argument list '(CC_CLASS_ENUM, )'`

**Comment by foobarbecue** [comment]
Just to confirm in case it's helpful, I'm using QT 5.12.1 with visual studio 2016 64, and my compile failed as described (C2666) until I made this change.

**Comment by dgirardeau** [comment]
Okay let's keep it as it doesn't do any harm and I guess the 5.12 version will be used by a lot of people from now one...
