### ISSUE TITLE
EIGEN_ALIGN16 wont work with eigen>=3.4

### ISSUE THREAD

**Issue by bartoszek** [CloudCompare/CloudCompare#1505]
As `eigen:3.4.0` now uses `alignas()` from `CPP11` spec, current struct declaration in
`plugins/core/Standard/qPCL/PclUtils/utils/my_point_types.h` are no longer valid.

```cpp
../cloudcompare/plugins/core/Standard/qPCL/PclUtils/utils/my_point_types.h:107:3: error: 'alignas' attribute only applies to variables, data members and tag types
} EIGEN_ALIGN16;
  ^
/usr/include/eigen3/Eigen/src/Core/util/ConfigureVectorization.h:153:23: note: expanded from macro 'EIGEN_ALIGN16'
#define EIGEN_ALIGN16 EIGEN_ALIGN_TO_BOUNDARY(16)
                      ^
/usr/include/eigen3/Eigen/src/Core/util/ConfigureVectorization.h:40:38: note: expanded from macro 'EIGEN_ALIGN_TO_BOUNDARY'
#define EIGEN_ALIGN_TO_BOUNDARY(n) alignas(n)
```
my_env:`{gcc:11.1.0,eigen:3.4.0,pcl:1.11.1}`
rationale: http://eigen.tuxfamily.org/index.php?title=3.4#Improvements_to_Eigen_Core

Quick solution (all tested):
* add `-DEIGEN_HAS_ALIGNAS=0` to `CXXFLAGS` to force old behavior 🧠 
* get rid of alignment in `qPCL` plugin altogether 🦆
