### ISSUE TITLE
Compiler error: 's_oculus' in ccGLWindow.cpp

### ISSUE THREAD

**Issue by dbworth** [CloudCompare/CloudCompare#574]
## Current Behavior

I am trying to compile the latest trunk without Oculus support and it fails to compile.

The compiler error:  
```
Generating moc_ccGLWidget.cpp
Generating moc_ccGLWindow.cpp
[ 45%] Built target QCC_GL_LIB_automoc
Scanning dependencies of target QCC_GL_LIB
[ 45%] Building CXX object libs/qCC_glWindow/CMakeFiles/QCC_GL_LIB.dir/ccRenderingTools.cpp.o
[ 46%] Building CXX object libs/qCC_glWindow/CMakeFiles/QCC_GL_LIB.dir/ccGLWindow.cpp.o
/home/dbutterworth/Software/trunk/libs/qCC_glWindow/ccGLWindow.cpp: In member function ‘void ccGLWindow::paintGL()’:
/home/dbutterworth/Software/trunk/libs/qCC_glWindow/ccGLWindow.cpp:1521:6: error: ‘s_oculus’ was not declared in this scope
   || s_oculus.mirror.texture
      ^
make[2]: *** [libs/qCC_glWindow/CMakeFiles/QCC_GL_LIB.dir/ccGLWindow.cpp.o] Error 1
make[1]: *** [libs/qCC_glWindow/CMakeFiles/QCC_GL_LIB.dir/all] Error 2
make: *** [all] Error 2
```

On line 1521, 's_oculus' is used outside of a   
`#ifdef CC_OCULUS_SUPPORT`
block in  
`libs/qCC_glWindow/ccGLWindow.cpp`  
```
	if (	!m_stereoModeEnabled
		||	m_stereoParams.glassType != StereoParams::OCULUS
		||	s_oculus.mirror.texture
		)
	{
		m_context->swapBuffers(this);
	}

```
## Expected Behavior

It should compile without error :-)

## Steps to Reproduce (for bugs)

Try to compile on Ubuntu 14.04, using CMake 3 and Qt 5.5.  
Run cmake-gui to configure,  
use default options with Oculus support disabled,  
go to build directory,  
cmake .  
make  

## Your Environment
Ubuntu 14.04, using CMake 3 and Qt 5.5  
CloudCompare latest trunk from github.

**Comment by asmaloney** [comment]
Thanks!
